# ??????
server:
  # ????HTTP??????8080
  port: 8080

gemini:
  # key???????
  key: AIzaSyCcol-ISrFcj0ozIfJDUt7xImLERf2kfss
  # ?????? true or false
  proxy: true
  # ????
  proxyIp: 127.0.0.1
  # ????
  proxyPort: 7890
